from copy import deepcopy


_CATALOG = {
    "ar": [
        {
            "key": "letter_discrimination",
            "title": "تمييز الحروف",
            "description": "اختر الحرف الصحيح من بين حروف متشابهة بصرياً.",
            "supports_audio": False,
            "interaction": "single_choice",
            "reward_points": 18,
            "reward_xp": 24,
            "rounds": [
                {
                    "prompt": "اختر الحرف المطابق",
                    "display_text": "ب",
                    "items": ["ب", "ت", "ث", "ن"],
                    "interaction": "single_choice",
                    "correct_answer": "ب",
                    "feedback": "أحسنت. ركز دائماً على عدد النقاط ومكانها.",
                },
                {
                    "prompt": "اختر الحرف المطابق",
                    "display_text": "ج",
                    "items": ["ح", "ج", "خ", "د"],
                    "interaction": "single_choice",
                    "correct_answer": "ج",
                    "feedback": "ممتاز. النقطة هي المفتاح هنا.",
                },
                {
                    "prompt": "اختر الحرف المطابق",
                    "display_text": "ص",
                    "items": ["ض", "ص", "س", "ش"],
                    "interaction": "single_choice",
                    "correct_answer": "ص",
                    "feedback": "رائع. الشكل العام مع النقاط يساعدك على التمييز.",
                },
                {
                    "prompt": "اختر الحرف المطابق",
                    "display_text": "ذ",
                    "items": ["د", "ر", "ذ", "ز"],
                    "interaction": "single_choice",
                    "correct_answer": "ذ",
                    "feedback": "إجابة صحيحة. لاحظ النقطة فوق الحرف.",
                },
            ],
        },
        {
            "key": "word_building",
            "title": "بناء الكلمات",
            "description": "رتب الحروف لتكوين الكلمة الصحيحة مع دعم صوتي.",
            "supports_audio": True,
            "interaction": "ordered_tiles",
            "reward_points": 20,
            "reward_xp": 28,
            "rounds": [
                {
                    "prompt": "رتب الحروف لتكوين الكلمة",
                    "display_text": "كلمة من 3 حروف",
                    "items": ["ر", "ق", "م"],
                    "audio_text": "قمر",
                    "interaction": "ordered_tiles",
                    "correct_answer": ["ق", "م", "ر"],
                    "feedback": "قمر كلمة جميلة. الترتيب الصحيح يبدأ بالقاف.",
                },
                {
                    "prompt": "رتب الحروف لتكوين الكلمة",
                    "display_text": "كلمة من 4 حروف",
                    "items": ["ت", "ك", "ا", "ب"],
                    "audio_text": "كتاب",
                    "interaction": "ordered_tiles",
                    "correct_answer": ["ك", "ت", "ا", "ب"],
                    "feedback": "أحسنت. الاستماع للكلمة يساعد على ترتيب الحروف.",
                },
                {
                    "prompt": "رتب الحروف لتكوين الكلمة",
                    "display_text": "كلمة من 3 حروف",
                    "items": ["ي", "ت", "ب"],
                    "audio_text": "بيت",
                    "interaction": "ordered_tiles",
                    "correct_answer": ["ب", "ي", "ت"],
                    "feedback": "بيت تبدأ بحرف الباء ثم الياء ثم التاء.",
                },
                {
                    "prompt": "رتب الحروف لتكوين الكلمة",
                    "display_text": "كلمة من 3 حروف",
                    "items": ["ر", "ن", "و"],
                    "audio_text": "نور",
                    "interaction": "ordered_tiles",
                    "correct_answer": ["ن", "و", "ر"],
                    "feedback": "رائع. النون ثم الواو ثم الراء.",
                },
            ],
        },
        {
            "key": "missing_letter",
            "title": "الحرف الناقص",
            "description": "أكمل الكلمة باختيار الحرف أو المقطع المناسب.",
            "supports_audio": False,
            "interaction": "single_choice",
            "reward_points": 16,
            "reward_xp": 22,
            "rounds": [
                {
                    "prompt": "أكمل الكلمة بالحرف الصحيح",
                    "display_text": "ك_اب",
                    "items": ["ت", "ب", "د"],
                    "interaction": "single_choice",
                    "correct_answer": "ت",
                    "feedback": "كتاب تكتمل بحرف التاء.",
                },
                {
                    "prompt": "أكمل الكلمة بالحرف الصحيح",
                    "display_text": "ق_م",
                    "items": ["ل", "ر", "د"],
                    "interaction": "single_choice",
                    "correct_answer": "ل",
                    "feedback": "قلم تكتب بالقاف ثم اللام ثم الميم.",
                },
                {
                    "prompt": "أكمل الكلمة بالمقطع الصحيح",
                    "display_text": "سي__ة",
                    "items": ["را", "كت", "مو"],
                    "interaction": "single_choice",
                    "correct_answer": "را",
                    "feedback": "سيارة تحتاج إلى المقطع را.",
                },
                {
                    "prompt": "أكمل الكلمة بالحرف الصحيح",
                    "display_text": "ش_س",
                    "items": ["م", "ن", "ر"],
                    "interaction": "single_choice",
                    "correct_answer": "م",
                    "feedback": "شمس تكتمل بحرف الميم.",
                },
            ],
        },
        {
            "key": "sound_to_word",
            "title": "من الصوت إلى الكلمة",
            "description": "استمع للصوت ثم اختر الكلمة المكتوبة الصحيحة.",
            "supports_audio": True,
            "interaction": "single_choice",
            "reward_points": 18,
            "reward_xp": 24,
            "rounds": [
                {
                    "prompt": "استمع واختر الكلمة الصحيحة",
                    "audio_text": "شمس",
                    "items": ["شمس", "سمك", "قلم"],
                    "interaction": "single_choice",
                    "correct_answer": "شمس",
                    "feedback": "ممتاز. طابقنا الصوت مع الكلمة الصحيحة.",
                },
                {
                    "prompt": "استمع واختر الكلمة الصحيحة",
                    "audio_text": "قمر",
                    "items": ["قلم", "قمر", "تمر"],
                    "interaction": "single_choice",
                    "correct_answer": "قمر",
                    "feedback": "أحسنت. استمع لأول وآخر صوت في الكلمة.",
                },
                {
                    "prompt": "استمع واختر الكلمة الصحيحة",
                    "audio_text": "بيت",
                    "items": ["نهر", "بيت", "ورد"],
                    "interaction": "single_choice",
                    "correct_answer": "بيت",
                    "feedback": "إجابة صحيحة. الكلمة المنطوقة هي بيت.",
                },
                {
                    "prompt": "استمع واختر الكلمة الصحيحة",
                    "audio_text": "نور",
                    "items": ["نور", "نار", "باب"],
                    "interaction": "single_choice",
                    "correct_answer": "نور",
                    "feedback": "رائع. كلمة نور تبدأ بالنون وتنتهي بالراء.",
                },
            ],
        },
        {
            "key": "sequencing",
            "title": "لعبة التسلسل",
            "description": "رتب الحروف أو المقاطع أو الأرقام بالترتيب الصحيح.",
            "supports_audio": False,
            "interaction": "ordered_tiles",
            "reward_points": 20,
            "reward_xp": 26,
            "rounds": [
                {
                    "prompt": "رتب الأرقام من الأصغر إلى الأكبر",
                    "display_text": "ابدأ بالرقم الأصغر",
                    "items": ["٣", "١", "٤", "٢"],
                    "interaction": "ordered_tiles",
                    "correct_answer": ["١", "٢", "٣", "٤"],
                    "feedback": "ترتيب الأرقام الصحيح يساعد على بناء التسلسل.",
                },
                {
                    "prompt": "رتب المقاطع لتكوين الكلمة",
                    "display_text": "كوّن كلمة: حافلة",
                    "items": ["فل", "ة", "حا"],
                    "interaction": "ordered_tiles",
                    "correct_answer": ["حا", "فل", "ة"],
                    "feedback": "حافلة تتكوّن من ثلاثة مقاطع مرتبة.",
                },
                {
                    "prompt": "رتب الحروف لتكوين تسلسل صحيح",
                    "display_text": "كوّن كلمة: علم",
                    "items": ["م", "ع", "ل"],
                    "interaction": "ordered_tiles",
                    "correct_answer": ["ع", "ل", "م"],
                    "feedback": "الترتيب الصحيح هو ع ثم ل ثم م.",
                },
                {
                    "prompt": "رتب الأرقام من الأصغر إلى الأكبر",
                    "display_text": "رتب المجموعة التالية",
                    "items": ["٦", "٨", "٥", "٧"],
                    "interaction": "ordered_tiles",
                    "correct_answer": ["٥", "٦", "٧", "٨"],
                    "feedback": "ممتاز. أنت تتبع النمط العددي جيداً.",
                },
            ],
        },
    ],
    "en": [
        {
            "key": "letter_discrimination",
            "title": "Letter Match",
            "description": "Choose the correct letter from a visually similar group.",
            "supports_audio": False,
            "interaction": "single_choice",
            "reward_points": 18,
            "reward_xp": 24,
            "rounds": [
                {
                    "prompt": "Pick the matching letter",
                    "display_text": "b",
                    "items": ["b", "d", "p", "q"],
                    "interaction": "single_choice",
                    "correct_answer": "b",
                    "feedback": "Great. Look at the stem direction and the bowl shape.",
                },
                {
                    "prompt": "Pick the matching letter",
                    "display_text": "m",
                    "items": ["m", "n", "w", "h"],
                    "interaction": "single_choice",
                    "correct_answer": "m",
                    "feedback": "Nice work. Count the bumps carefully.",
                },
                {
                    "prompt": "Pick the matching letter",
                    "display_text": "g",
                    "items": ["q", "y", "g", "j"],
                    "interaction": "single_choice",
                    "correct_answer": "g",
                    "feedback": "Correct. Focus on the lower loop shape.",
                },
                {
                    "prompt": "Pick the matching letter",
                    "display_text": "t",
                    "items": ["f", "l", "t", "i"],
                    "interaction": "single_choice",
                    "correct_answer": "t",
                    "feedback": "Excellent. The cross-bar helps identify the letter.",
                },
            ],
        },
        {
            "key": "word_building",
            "title": "Word Builder",
            "description": "Drag letters into the right order with audio support.",
            "supports_audio": True,
            "interaction": "ordered_tiles",
            "reward_points": 20,
            "reward_xp": 28,
            "rounds": [
                {
                    "prompt": "Arrange the letters to build the word",
                    "display_text": "3 letters",
                    "items": ["a", "c", "t"],
                    "audio_text": "cat",
                    "interaction": "ordered_tiles",
                    "correct_answer": ["c", "a", "t"],
                    "feedback": "Cat begins with c, then a, then t.",
                },
                {
                    "prompt": "Arrange the letters to build the word",
                    "display_text": "5 letters",
                    "items": ["n", "t", "i", "a", "r"],
                    "audio_text": "train",
                    "interaction": "ordered_tiles",
                    "correct_answer": ["t", "r", "a", "i", "n"],
                    "feedback": "Listening to each sound helps place the letters.",
                },
                {
                    "prompt": "Arrange the letters to build the word",
                    "display_text": "4 letters",
                    "items": ["o", "b", "o", "k"],
                    "audio_text": "book",
                    "interaction": "ordered_tiles",
                    "correct_answer": ["b", "o", "o", "k"],
                    "feedback": "Book has two o letters in the middle.",
                },
                {
                    "prompt": "Arrange the letters to build the word",
                    "display_text": "3 letters",
                    "items": ["u", "s", "n"],
                    "audio_text": "sun",
                    "interaction": "ordered_tiles",
                    "correct_answer": ["s", "u", "n"],
                    "feedback": "Sun is a short word with three sounds.",
                },
            ],
        },
        {
            "key": "missing_letter",
            "title": "Missing Letter",
            "description": "Complete the word with the missing letter or syllable.",
            "supports_audio": False,
            "interaction": "single_choice",
            "reward_points": 16,
            "reward_xp": 22,
            "rounds": [
                {
                    "prompt": "Complete the word",
                    "display_text": "c_t",
                    "items": ["a", "o", "u"],
                    "interaction": "single_choice",
                    "correct_answer": "a",
                    "feedback": "Cat needs the letter a.",
                },
                {
                    "prompt": "Complete the word",
                    "display_text": "tr__n",
                    "items": ["ai", "ee", "oa"],
                    "interaction": "single_choice",
                    "correct_answer": "ai",
                    "feedback": "Train is completed with the syllable ai.",
                },
                {
                    "prompt": "Complete the word",
                    "display_text": "b__k",
                    "items": ["oo", "ee", "oa"],
                    "interaction": "single_choice",
                    "correct_answer": "oo",
                    "feedback": "Book uses double o in the middle.",
                },
                {
                    "prompt": "Complete the word",
                    "display_text": "s_n",
                    "items": ["u", "a", "i"],
                    "interaction": "single_choice",
                    "correct_answer": "u",
                    "feedback": "Sun is completed with the letter u.",
                },
            ],
        },
        {
            "key": "sound_to_word",
            "title": "Sound to Word",
            "description": "Listen to a sound or word, then choose the matching word.",
            "supports_audio": True,
            "interaction": "single_choice",
            "reward_points": 18,
            "reward_xp": 24,
            "rounds": [
                {
                    "prompt": "Listen and choose the correct word",
                    "audio_text": "cat",
                    "items": ["cat", "cut", "cap"],
                    "interaction": "single_choice",
                    "correct_answer": "cat",
                    "feedback": "Great listening. The final sound is t.",
                },
                {
                    "prompt": "Listen and choose the correct word",
                    "audio_text": "train",
                    "items": ["drain", "train", "trail"],
                    "interaction": "single_choice",
                    "correct_answer": "train",
                    "feedback": "Nice. Focus on the opening tr sound.",
                },
                {
                    "prompt": "Listen and choose the correct word",
                    "audio_text": "book",
                    "items": ["book", "back", "bake"],
                    "interaction": "single_choice",
                    "correct_answer": "book",
                    "feedback": "Correct. The middle vowel sound matches book.",
                },
                {
                    "prompt": "Listen and choose the correct word",
                    "audio_text": "sun",
                    "items": ["son", "sun", "sand"],
                    "interaction": "single_choice",
                    "correct_answer": "sun",
                    "feedback": "Well done. The short u sound points to sun.",
                },
            ],
        },
        {
            "key": "sequencing",
            "title": "Sequencing Game",
            "description": "Order letters, syllables, or numbers in the correct sequence.",
            "supports_audio": False,
            "interaction": "ordered_tiles",
            "reward_points": 20,
            "reward_xp": 26,
            "rounds": [
                {
                    "prompt": "Order the numbers from smallest to largest",
                    "display_text": "Start with the smallest number",
                    "items": ["3", "1", "4", "2"],
                    "interaction": "ordered_tiles",
                    "correct_answer": ["1", "2", "3", "4"],
                    "feedback": "Perfect. Number order builds strong sequencing habits.",
                },
                {
                    "prompt": "Order the syllables to build the word",
                    "display_text": "Build the word: reading",
                    "items": ["ing", "read"],
                    "interaction": "ordered_tiles",
                    "correct_answer": ["read", "ing"],
                    "feedback": "Reading starts with read and ends with ing.",
                },
                {
                    "prompt": "Order the letters to build the word",
                    "display_text": "Build the word: lamp",
                    "items": ["m", "a", "l", "p"],
                    "interaction": "ordered_tiles",
                    "correct_answer": ["l", "a", "m", "p"],
                    "feedback": "Lamp follows the sequence l-a-m-p.",
                },
                {
                    "prompt": "Order the numbers from smallest to largest",
                    "display_text": "Put the pattern in order",
                    "items": ["8", "5", "7", "6"],
                    "interaction": "ordered_tiles",
                    "correct_answer": ["5", "6", "7", "8"],
                    "feedback": "Excellent. You kept the number pattern in order.",
                },
            ],
        },
    ],
}


def _normalized_locale(locale: str) -> str:
    return "en" if locale == "en" else "ar"


def list_games(locale: str) -> list[dict]:
    normalized = _normalized_locale(locale)
    items = []
    for record in _CATALOG[normalized]:
        item = deepcopy(record)
        item.pop("rounds", None)
        items.append(item)
    return items


def get_game(locale: str, game_key: str) -> dict | None:
    normalized = _normalized_locale(locale)
    for record in _CATALOG[normalized]:
        if record["key"] == game_key:
            return deepcopy(record)
    return None
